### ISSUE TITLE
Agregar funcionalidad de copiar a portapapeles

### ISSUE THREAD

**Issue by ricardoerl** [ricardoerl/svstamp#1]
La idea es que el usuario pueda copiar fácilmente alguna información del stamp, por ejemplo:
- Copiar enlace de link original
- Copiar enlace de tweetstamp
- Copiar el usuario del tweet

**Comment by ralegria** [comment]
I will be working on this one during the next weekend.

**Comment by ricardoerl** [comment]
@ralegria Awesome! Let me know if you need more details or if you have any question. 🙌

**Comment by ricardoerl** [comment]
@ralegria agregué unos cambios relacionados en #22, agradecería tu opinión y sugerencias. 🙌
