### ISSUE TITLE
Agregar configuración de Prettier y ESLint

### ISSUE THREAD

**Issue by ricardoerl** [ricardoerl/svstamp#10]
Para mantener consistencia, se deberia tener una configuración general para formato y correción de código.

**Comment by guillegr123** [comment]
¿Puedo tomar este issue?

**Comment by ricardoerl** [comment]
@guillegr123 Hola Guille, justo ya había comenzado en este issue para tenerlo antes de cualquier otra contribución, ¿te parece si me ayudas para darle una revisión y ver como se mejora?
