### ISSUE TITLE
Agregar soporte para Typescript

### ISSUE THREAD

**Issue by rocinante42** [ricardoerl/svstamp#12]
**Next.js** ya trae soporte built-in para typescript a partir de la version 9, solo se necesita crear un archivo `tsconfig.json` en el root del proyecto.

Como Typescript es un superset de Javascript, se pueden dejar los archivos .js y funcionará perfectamente la app. Sugiero ir migrando lentamente empezando con los componentes más pequeños, instalando paquetes de @types que hagan falta y terminar con el entry page de la aplicación.

**Comment by rocinante42** [comment]
Ahora que lo pienso, creo que la mejor estrategia es al revés, empezar con el entry point e ir cambiando componentes poco a poco. TS puede consumir JS pero no estoy seguro que funcione al revés.

**Comment by ricardoerl** [comment]
Me parece el plan, la ventaja por el momento es que son pocos componentes y la migración puede ir avanzando más rápido. El primer paso seria agregar la configuración y temas de linting, luego podemos comenzar con `pages/index.js`
